import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Lookupon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
      <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
